### ISSUE TITLE
Significant discrepancies between reported and actual memory usage

### ISSUE THREAD

**Issue by danielyli** [thewtex/tmux-mem-cpu-load#38]
tmux-mem-cpu-load seems to consistently under-report my memory usage.  As an extreme example, I've attached a screenshot of my memory usages as reported by OS X's Activity Monitor alongside tmux-mem-cpu-load's reported usage; you'll notice that OS X reports that I'm usually almost all my physical memory (and aggressively swapping almost 12 GB) while tmux-mem-cpu-load reports that I'm using only 1.4 GB.

I can confirm that when taking this screenshot my system was _very_ sluggish, which leads me to believe OS X's reporting is the correct one.

As a side note, I also noticed that the CPU load averages are incorrect.  My system load before and after this screenshot was consistently in the 30–50% for about an hour (the instantaneous screenshot here doesn't show it), but the running averages never moved past 2.xx%.

I'm running OS X El Capitan 10.11.5 on a MacBook Air with 4 GB physical memory.

![tmux-cpu-mem inconsistency](https://cloud.githubusercontent.com/assets/1744438/15687275/b26d7d1c-2728-11e6-97ba-f90c0b2ac74c.png)

**Comment by l0ner** [comment]
This is because we are counting only `vm_stats.active_count` (App Memory) and `vm_stats.wire_count` (Wired memory) towards used memory. Adding `vm_stat.inactive_count` to the count might solve this problem. I don't use OSX anymore nor I have hardware to run it on, so I'm shooting in the dark and guessing that it should be the "Compressed Memory". This: http://stackoverflow.com/a/1911863 seems to be confirming my hunch though. 

If it's not this then I don't know. Maye some other member of the `vm_statistics` (http://opensource.apple.com/source/xnu/xnu-1504.7.4/osfmk/mach/vm_statistics.h) struct?

Also another method for getting the count of used memory might be accessing the members of `task_basic_info` struct (http://opensource.apple.com/source/xnu/xnu-1504.7.4/osfmk/mach/task_info.h) for the kernel itself:

```c
float getMemoryUsage() {
	struct task_basic_info info;
	mach_msg_type_number_t size = sizeof(info);
	if( KERN_SUCCESS ==  task_info(mach_task_self(),
		TASK_BASIC_INFO, (task_info_t)&info, &size) 
          ) 
        return ((float)info.resident_size/1048576.0f);
	else 
        return 0;
}
```

This might be unreliable though.

Source: http://forum.sparrow-framework.org/topic/checking-device-memory-and-current-running-process#post-7738

While this solution is for iOS is should wotk on OSX too since the kernel and base libs are the same.

Could you run something like top/htop and tell how much used memory you see there.

BTW pure curiosity: what app is using 21Gb of RAM?

The fact you are getting incorrect load averages is strange, since we are using a functions that's provided directly by Apple (http://opensource.apple.com/source/Libc/Libc-262/gen/getloadavg.c) to get them. Again, use something like htop to compare.
