### ISSUE TITLE
Not showing at first config load

### ISSUE THREAD

**Issue by fam4r** [thewtex/tmux-mem-cpu-load#53]
Hi,

installed with tpm, so I used the example found in the [installation guide](https://github.com/thewtex/tmux-mem-cpu-load#configuring-tmux):

```
set -g status-right "#[fg=green]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]"
```

It works, but only if I reload tmux configuration. So at first tmux startup, it doesn't show anything. Other plugin works.

I compared with a friend's tmux configuration and he is using the same tmux command, but with single quote. I tried and it works instantly.
To be clear, above example, rewritten with single quote (see below), works without reloading tmux configuration:

```
set -g status-right '#[fg=green]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]'
```

How it's possible?

tmux version: `2.6`

**Comment by fam4r** [comment]
Is this project abandoned?

**Comment by l0ner** [comment]
Abandoned not really, just stable, and thus not requiring much attention nor active developement.

As for your questions, I really have no idea. Maybe try replacing your double quotes with single quotes?

please also note that in order to provide you with cpu usage, this monitor needs to sample some cpu usage data. Maybe it hangs somewhere.

So, after firing up tmux, is a tmux-mem-cpu-load process created? (fire up somthing like htop/top and watch if the process appears/dissapears or is simply there). Normal behaviour for tmux-mem-cpu-load would be:

1. Start
2. Gather Data
3. Digest the data
4. Print output
5. End

By doing this:

```bash
while (true) do; clear; ps aux | grep "tmux-mem"; sleep 1; done
```

And monitorig the pid of the tmux-mem-cpu-load you should see wheter it executes as it should or is hung up, and thus not producing output.

**Comment by julenpardo** [comment]
I was facing the same problem and replacing the double quotes with single quotes for the `status-right` value worked for me.

**Comment by fam4r** [comment]
Thank you @l0ner for your answer.

As I wrote in my first post I solved just by using single quotes instead of double quotes, like you said.

I opened the issue to inform other people facing the same problem and to ask developers why that is happening.

I also tried your commands and:
- using single quotes, the process is created and that's what I get: 
```
/home/famar/.tmux/plugins//tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2
grep --color tmux-mem
```
- using double quotes I only get prompted `grep` process infos

Yes, I forgot to specify that I only tried in `status-right` value.
